### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by wessuttle** [DavidNKraemer/SoCG21#11]
Not sure what happened here:
![plot_error](https://user-images.githubusercontent.com/6924517/107680942-77604e00-6c6c-11eb-871b-f61fee5aaa6e.png)
Any ideas?

**Comment by LoganDGraham** [comment]
Can you check that you input the obstacles as a numpy array of numpy arrays?

Should look like this:
obstacles = np.array([[3,3], [0,1]])

**Comment by LoganDGraham** [comment]
Ohhhhh. I got it. There's a small error because the obstacles array had length 0. I'll push a fix to dev ASAP

**Comment by LoganDGraham** [comment]
It works now. If you want there to be no obstacles, then write

`obstacles = np.array([[]])`
