### ISSUE TITLE
Neighborhood radii

### ISSUE THREAD

**Issue by wessuttle** [DavidNKraemer/SoCG21#7]
Where should the neighborhood radius be set? It's currently hard-coded to 1 in a couple different places. @LoganDGraham @DavidNKraemer

**Comment by DavidNKraemer** [comment]
In my opinion it should sit somewhere as an attribute in `DistributedBoard`.

**Comment by wessuttle** [comment]
I changed it so `neighborhood_radius=1` is passed to `DistributedBoard` on initialization. Also changed the corresponding calls to `neighborhood` in `Agent`.
